### ISSUE TITLE
Can't make the "git submodule update" due to access rights on github

### ISSUE THREAD

**Issue by ghost** [duniter/upycoin#3]
Clonage dans 'ucoin'...
The authenticity of host 'github.com (192.30.252.129)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.

Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.129' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Le clonage de 'git@github.com:ucoin-io/ucoin-python-api.git' dans le chemin de sous-module 'ucoin' a échoué

**Comment by sbDevGit** [comment]
mkdir ucoin && cd ucoin && git clone https://github.com/ucoin-io/ucoin-python-api/

**Comment by ghost** [comment]
ah , I need to add a public key to my github account ! ;o
